### PR TITLE
Utilise tuples to fix function types

### LINKED ISSUE #44: investigate "strictFunctionTypes" issue

### PR DESCRIPTION
**Pull request by Carl-Foster**
I set this up to see if I could use tuple types to fix some of the lingering issues. I think this has fixed it although I'm not 100% sure.

I think this fixes #44 and #63 but does require a bump in TypeScript version

### CODE REVIEW

**Comment by Carl-Foster** [comment]
@piotrwitek Any thoughts on this?

**Comment by openscript** [comment]
This works for me. Thank you @Carl-Foster.

**Comment by travigd** [comment]
@piotrwitek Don't mean to bother, but any update on this?

**Comment by piotrwitek** [comment]
For the moment this is blocked, first I need to finish rewrite of type-testing suite to `dts-jest` because the utility we're using right now is really poor (written by me like a year ago when type-testing wasn't really a thing yet!).

I already rewritten my other library `utility-types` and it's super cool. Should be ready in few days, then I can come back here.

**Comment by piotrwitek** [comment]
Thanks for a quick response @Carl-Foster, there'll be quite a lot :) So please wait a bit more as for the moment I cannot predict exactly what I'll end up with. I'll see tomorrow.

**Comment by piotrwitek** [comment]
Hey, after the analysis the only useful part here is the simplification of overloads in `is-action-of.ts` file. Strict Function types were fixed on typesafe-actions@2.x.x release line that is still working with previous TS v2.9. This change however require recent TS v3.0 which can be shipped on recently upgraded 3.x.x release line.

The simplification using tuples looks good from code maintenance perspective and shouldn't change any behaviour of the library type-wise. We need to rebase it and discard all other changes except is-action-of.ts file refactoring.

I have just added new type tests cases with type-tests snapshots using new test suite just to be sure that all previous use-cases are still covered and it is not breaking anything.

**Comment by piotrwitek** [comment]
Closing as implemented: bab3528abe7cc3c23315e058a52b381f03c29c68

**Pull request closed without merging**
