### PR TITLE
update readme for StateType

### PR DESCRIPTION
**Pull request by evollu**
Current example doesn't work

### CODE REVIEW

**Comment by piotrwitek** [comment]
working just fine
screen shot 2018-05-26 at 3 41 23 pm

**Comment by piotrwitek** [comment]
https://codesandbox.io/s/github/piotrwitek/typesafe-actions-todo-app

**Comment by evollu** [comment]
it is because of redux 4?

**Comment by piotrwitek** [comment]
@evollu I'll add a combatibility note about redux < 4

**Pull request closed without merging**
